spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.94/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.1.94
    port: 6379
  freemarker:
    suffix: .ftl

server:
  servlet:
    context-path: /sell
  port: 8080

wechat:
  mpAppId: wxc97880b2e5f2cddb
  mpAppSecret: e9fec42df7cb7936104540ad596e1d9b
  openAppId: wx666666xxxxxxxxxx      # 没有
  openAppSecret: 91ansdxxxxxxxxxxxxxx  # 没有
  mchId: 1483xxxxxxx  # 没有
  mchKey: 06C56A89949D617xxxxxxxxxxx  # 没有
  keyPath: D:\keypath\JSAPI.p12  # 没有
  notifyUrl: http://sellerebus.natapp1.cc/sell/pay/notify
  templateId:                  #模板id
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

projecturl:
  wechatMpAuthorize: http://sellerebus.natapp1.cc
  wechatOpenAuthorize: http://sellerebus.natapp1.cc
  sell: http://sellerebus.natapp1.cc
logging:
  level:
    com.mooc.sell.dataobject.mapper: trace
